### ? Devuelve todas los usuarios | TOKEN  | ROL: ADMIN
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjY0MGEyOTA1NGY3N2ZlODNlNzg4YyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2NTYxNzM3MjYsImV4cCI6MTY1NjE3NTUyNiwiaXNzIjoiY29taWRldiIsInN1YiI6ImFkbWluIn0.tUO9u-eQvxbh17oZ_VeTZ0VOFuXS5B4CaIFceyWzjPc


### ? Devuelve un usuario según el /id | TOKEN   | ROL: ADMIN, CLIENTE
GET http://localhost:3000/users/62b640a29054f77fe83e788c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjY0MGEyOTA1NGY3N2ZlODNlNzg4YyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2NTYxNzM3MjYsImV4cCI6MTY1NjE3NTUyNiwiaXNzIjoiY29taWRldiIsInN1YiI6ImFkbWluIn0.tUO9u-eQvxbh17oZ_VeTZ0VOFuXS5B4CaIFceyWzjPc


### ? Guardar un usuarios admin | TOKEN   | ROL: ADMIN
POST http://localhost:3000/users/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjhhM2NkMWQzMjMxYjMzYTc4NGMzMyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2NTYyNjk4NDAsImV4cCI6MTY1NjI3MTY0MCwiaXNzIjoiY29taWRldiIsInN1YiI6ImFkbWluIn0.W6t-X_tP6br-DRbGB-6FhjtrSHeDGVd1s0W2TMIMTtA

{
    "username" : "admin",
    "password" : "admin"
}


### ? Login (obtiene jwt)
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}

### ? Existe username (obtiene boolean)
POST http://localhost:3000/users/validate/username
Content-Type: application/json

{
    "username" : "existo?"
}


### ? Token refresh (obtiene jwt por Token refresh) | TOKEN-REFRESH
POST http://localhost:3000/users/token/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjY0MGEyOTA1NGY3N2ZlODNlNzg4YyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2NTYxNzM3MjYsImV4cCI6MTY1NjE3NTUyNiwiaXNzIjoiY29taWRldiIsInN1YiI6ImFkbWluIn0.tUO9u-eQvxbh17oZ_VeTZ0VOFuXS5B4CaIFceyWzjPc
