### Guardar una categoria | TOKEN | ROL: ADMIN
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYjY0MGEyOTA1NGY3N2ZlODNlNzg4YyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2NTYxNzAwOTcsImV4cCI6MTY1NjE3MTg5NywiaXNzIjoiY29taWRldiIsInN1YiI6ImFkbWluIn0.G3ELWlKZOKUbamcfJXUM9e50iiyCe9EImiwN1w7fAQ4

{
    "name": "Tecnologia"
}


### Ver todas las categorias
GET http://localhost:3000/categories

### Ver todas una categoria por ID
GET http://localhost:3000/categories/62b63129948f4631505acb35
