### Devuelve todas los productos
GET http://localhost:3000/products

### Devuelve un producto según el /id
GET http://localhost:3000/products/62b63515c9a8a590e014cd0f

### Elimina segun id
DELETE  http://localhost:3000/products/5


### Guardar un producto
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Producto n03",
    "description": "Producto productero",
    "stock": 100,
    "price": 150.5,
    "categoryName": "categoria con un nombre superlargo"
}
